//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfCatchingWorkSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int ID { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<int> RecordPlanID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual Plans Plans { get; set; }
    }
}
