//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfCatchingWorkSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePowers
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
