//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOfCatchingWorkSchedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusHistory
    {
        public int ID { get; set; }
        public Nullable<int> HistoryStatusID { get; set; }
        public int HistoryPlanID { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
    
        public virtual Plans Plans { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
